### ISSUE TITLE
[BUG]: Authentication Failure Causing AttributeError in Slackline Application

### ISSUE THREAD

**Issue by SharanGoharKhan** [talboren/slackline#2]
### Description of the bug

Issue:
When attempting to run the Slackline application, users encounter a traceback error indicating an AttributeError. The error specifically points to an issue within the get_team_name() function in the slackline.py file.

Error Message:

```
Traceback (most recent call last):
  File "/Users/sharangoharkhan/Projects/slackline-o/slackline.py", line 181, in <module>
    main()
  File "/Users/sharangoharkhan/Projects/slackline-o/slackline.py", line 162, in main
    team_name = get_team_name()
                ^^^^^^^^^^^^^^^
  File "/Users/sharangoharkhan/Projects/slackline-o/slackline.py", line 27, in get_team_name
    return response_json.get('team').get('name')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

Investigation:

Upon further investigation, it has been discovered that the response_json object contains {'ok': False, 'error': 'invalid_auth'}, indicating an authentication failure with Slack's endpoint. This suggests that valid authentication keys have been provided, but there might be an issue either at the user's end or a potential bug in the Slackline application.

### Steps To Reproduce

**Steps to Reproduce:**
1- Ensure that valid Slack API keys are configured in the application.
2- Run the Slackline application.
**Expected Behavior:**
The application should authenticate successfully, and the response_json object should contain information about the Slack team.

**Expected Behavior:**
The application should authenticate successfully, and the response_json object should contain information about the Slack team.

**Actual Behavior:**
The application fails to authenticate, resulting in an AttributeError as described above.

**Possible Causes:**

1- Incorrectly configured Slack API keys.
2- Changes in Slack's authentication mechanism.
3- Bug in the Slackline application.

**Recommended Actions:**

1- Double-check the provided Slack API keys to ensure they are accurate.
2- Verify that the Slackline application is using the correct authentication process.
3- Check for any updates or patches related to changes in Slack's API or authentication methods.
4- nvestigate the Slackline application code for potential issues related to authentication handling.

**Environment Details:**

* Operating System: macOS
* Python Version:  Python 3.8]
* Slackline Version: latest

### Additional Information

<img width="682" alt="Screenshot 2024-01-04 at 10 33 26 PM" src="https://github.com/talboren/slackline/assets/11601690/7929c787-715c-4555-983b-105bcfafe431">

**Comment by SharanGoharKhan** [comment]
It work using `D_TOKEN` instead of `D_COOKIE`
